import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../frontend/header";
import Footer from "../frontend/footer";
import QuizModal from "../frontend/PopupQuiz";
import Script from "next/script";

import { Plus_Jakarta_Sans, Space_Grotesk, DM_Sans } from 'next/font/google'

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-heading',
  display: 'swap',
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-accent',
  display: 'swap',
})

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-body',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        src="https://t.contentsquare.net/uxa/586d1bfbb5898.js"
      />
      <body
        className={`${plusJakartaSans.variable} ${spaceGrotesk.variable} ${dmSans.variable}`}
      >
        <Navbar />
        <QuizModal />
        {children}
        <Footer />
      </body>
    </html>
  );
}
